export enum ListActionType {
    ADD_NEW_CARD = 'ADD_NEW_CARD',
    ADD_NEW_COLUMN = 'ADD_NEW_COLUMN ',
    UPDATE_CARD = 'UPDATE_CARD',
    UPDATE_CARD_COLUMN = 'UPDATE_CARD_COLUMN',
    DELETE_COLUMN = 'DELETE_COLUMN',
    DELETE_CARD = 'DELETE_CARD',
}
